---
title: "HW Class 6"
author: "Vina Nguyen A16151678"
date: "2023-05-01"
output: html_document
---

We are creating our own functions in this assignment. 

```{r}
# Can you improve this analysis code?
library(bio3d)
s1 <- read.pdb("4AKE") # kinase with drug
s2 <- read.pdb("1AKE") # kinase no drug
s3 <- read.pdb("1E4Y") # kinase with drug
s1.chainA <- trim.pdb(s1, chain="A", elety="CA")
s2.chainA <- trim.pdb(s2, chain="A", elety="CA")
s3.chainA <- trim.pdb(s1, chain="A", elety="CA")
s1.b <- s1.chainA$atom$b
s2.b <- s2.chainA$atom$b
s3.b <- s3.chainA$atom$b
plotb3(s1.b, sse=s1.chainA, typ="l", ylab="Bfactor")
plotb3(s2.b, sse=s2.chainA, typ="l", ylab="Bfactor")
plotb3(s3.b, sse=s3.chainA, typ="l", ylab="Bfactor")
```

> Q6. How would you generalize the original code above to work with any set of input
protein structures?

We want to turn the given code snippets into a function that will take any of the three listed input proteins and plot the effect of drug binding.

```{r}

```


```{r}
protein_drug_plot <- function(file, chain, element, factor) {
  
}
```


```{r}
protein.drug.plot <- function()
```



